# Generated by Django 3.1 on 2023-02-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_user'),
        ('carts', '0003_auto_20210308_1648'),
    ]

    operations = [
    ]
